"""Identifier and secret generators."""

from __future__ import annotations

import math
import os
import secrets
import time
import uuid

from fastapi import APIRouter, Query
from pydantic import BaseModel

from ..errors import ToolError
from ..registry import Endpoint, ToolInfo, register

router = APIRouter(prefix="/v1", tags=["idgen"])

_CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_NANOID_ALPHABET = "_-0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

_WORDS = [
    "able",
    "acid",
    "apex",
    "army",
    "atom",
    "aunt",
    "bake",
    "bald",
    "bank",
    "barn",
    "beam",
    "bean",
    "bear",
    "beat",
    "beef",
    "bell",
    "belt",
    "bird",
    "blue",
    "boat",
    "body",
    "bold",
    "bone",
    "book",
    "boss",
    "both",
    "bulk",
    "bush",
    "cake",
    "calm",
    "cane",
    "cape",
    "cash",
    "cast",
    "cave",
    "chef",
    "chin",
    "clay",
    "clip",
    "club",
    "coal",
    "coat",
    "coin",
    "cold",
    "cook",
    "cool",
    "cord",
    "corn",
    "cost",
    "cove",
    "crew",
    "crop",
    "dark",
    "dawn",
    "deer",
    "desk",
    "dial",
    "dice",
    "dine",
    "disk",
    "dock",
    "dome",
    "door",
    "dove",
    "drum",
    "dust",
    "duty",
    "each",
    "earl",
    "earn",
    "east",
    "easy",
    "edge",
    "exit",
    "face",
    "fact",
    "fair",
    "farm",
    "fast",
    "fear",
    "fern",
    "film",
    "fine",
    "fire",
    "firm",
    "fish",
    "five",
    "flag",
    "flat",
    "flax",
    "flee",
    "flew",
    "flex",
    "flip",
    "flow",
    "foam",
    "fold",
    "folk",
    "font",
    "food",
    "foot",
    "fork",
    "form",
    "fort",
    "four",
    "free",
    "frog",
    "fuel",
    "full",
    "fund",
    "gain",
    "game",
    "gate",
    "gaze",
    "gear",
    "gift",
    "girl",
    "give",
    "glad",
    "glow",
    "goal",
    "goat",
    "gold",
    "golf",
    "gone",
    "good",
    "gray",
    "grew",
    "grid",
    "grim",
    "grip",
    "grow",
    "gulf",
    "hail",
    "hair",
    "half",
    "hall",
    "hand",
    "hard",
    "harm",
    "hawk",
    "haze",
    "head",
    "heal",
    "heap",
    "hear",
    "heat",
    "herb",
    "herd",
    "hero",
    "hide",
    "high",
    "hill",
    "hint",
    "hive",
    "hold",
    "hole",
    "holy",
    "home",
    "hood",
    "hook",
    "hope",
    "horn",
    "host",
    "hour",
    "huge",
    "hull",
    "hunt",
    "hurt",
    "icon",
    "idea",
    "idle",
    "inch",
    "iron",
    "isle",
    "item",
    "jade",
    "jail",
    "jazz",
    "jean",
    "joke",
    "jump",
    "junk",
    "keen",
    "keep",
    "kelp",
    "kept",
    "kick",
    "kind",
    "king",
    "kite",
    "knee",
    "knew",
    "knob",
    "knot",
    "lace",
    "lake",
    "lamb",
    "lamp",
    "land",
    "lane",
    "lava",
    "lawn",
    "lazy",
    "leaf",
    "leak",
    "lean",
    "leap",
    "left",
    "lend",
    "lens",
    "lily",
    "limb",
    "lime",
    "line",
    "link",
    "lion",
    "list",
    "live",
    "load",
    "loaf",
    "loan",
    "lock",
    "loft",
    "lone",
    "long",
    "look",
    "loop",
    "lord",
    "lose",
    "loss",
    "loud",
    "love",
    "luck",
    "lump",
    "lung",
    "lush",
    "mail",
    "main",
    "make",
    "male",
    "mall",
    "many",
    "mark",
    "mask",
    "mass",
    "mast",
    "mate",
    "math",
    "maze",
    "meal",
    "mean",
    "meat",
    "melt",
    "mesh",
    "mild",
    "mile",
    "milk",
    "mill",
    "mind",
    "mine",
    "mint",
    "mist",
    "moon",
    "moss",
    "most",
    "moth",
    "move",
    "much",
    "mule",
    "myth",
    "nail",
    "name",
    "navy",
    "near",
    "neat",
    "neck",
    "need",
    "nest",
    "news",
    "next",
    "nice",
    "node",
    "none",
    "noon",
    "norm",
    "nose",
    "note",
    "numb",
    "oath",
    "odor",
    "okay",
    "omit",
    "once",
    "only",
    "onto",
    "open",
    "oval",
    "oven",
    "owed",
    "owns",
    "pace",
    "pack",
    "page",
    "paid",
    "pain",
    "pair",
    "palm",
    "park",
    "part",
    "past",
    "path",
    "pave",
    "peak",
    "pear",
    "peer",
    "pile",
    "pill",
    "pine",
    "pink",
    "pint",
    "pipe",
    "plan",
    "play",
    "plot",
    "plow",
    "plug",
    "plum",
    "poem",
    "poet",
    "pole",
    "poll",
    "pond",
    "pony",
    "pool",
    "poor",
    "pork",
    "port",
    "pose",
    "post",
    "pour",
    "pray",
    "prep",
    "prey",
    "prom",
    "prop",
    "pull",
    "pump",
    "pure",
    "push",
    "quad",
    "quiz",
    "race",
    "rack",
    "raft",
    "rage",
    "rail",
    "rain",
    "rake",
    "ramp",
    "rank",
    "rare",
    "rate",
    "read",
    "real",
    "reap",
    "rear",
    "reef",
    "rely",
    "rest",
    "rice",
    "rich",
    "ride",
    "rife",
    "ring",
    "riot",
    "ripe",
    "rise",
    "risk",
    "road",
    "roam",
    "roar",
    "robe",
    "rock",
    "rode",
    "role",
    "roll",
    "roof",
    "room",
    "root",
    "rope",
    "rose",
    "rosy",
    "ruby",
    "rude",
    "ruin",
    "rule",
    "rush",
    "rust",
    "safe",
    "sage",
    "sail",
    "salt",
    "sand",
    "save",
    "scan",
    "seal",
    "seam",
    "seat",
    "seed",
    "self",
    "sell",
    "send",
    "ship",
    "shoe",
    "shop",
    "shot",
    "show",
    "shut",
    "sick",
    "side",
    "sift",
    "sign",
    "silk",
    "sing",
    "sink",
    "site",
    "size",
    "skin",
    "skip",
    "slab",
    "sled",
    "slid",
    "slim",
    "slip",
    "slot",
    "slow",
    "snap",
    "snow",
    "soak",
    "soap",
    "soar",
    "sock",
    "sofa",
    "soft",
    "soil",
    "sold",
    "sole",
    "solo",
    "song",
    "sons",
    "soon",
    "sort",
    "soul",
    "soup",
    "sour",
    "span",
    "spin",
    "spot",
    "spun",
    "stem",
    "step",
    "stir",
    "stop",
    "stow",
    "stub",
    "stud",
    "such",
    "suit",
    "sung",
    "sunk",
    "sure",
    "surf",
    "swam",
    "swan",
    "swap",
    "sway",
    "swim",
    "tail",
    "take",
    "tale",
    "talk",
    "tall",
    "tame",
    "tank",
    "tape",
    "task",
    "teak",
    "team",
    "tear",
    "tell",
    "tend",
    "tent",
    "term",
    "test",
    "text",
    "than",
    "that",
    "thaw",
    "thee",
    "them",
    "then",
    "they",
    "thin",
    "this",
    "thus",
    "tick",
    "tide",
    "tidy",
    "tile",
    "till",
    "tilt",
    "time",
    "tiny",
    "tips",
    "toad",
    "toe",
    "toll",
    "tomb",
    "tone",
    "tool",
    "toon",
    "toot",
    "torn",
    "toss",
    "tour",
    "town",
    "trap",
    "tray",
    "tree",
    "trek",
    "trim",
    "trip",
    "trod",
    "trot",
    "true",
    "tube",
    "tuck",
    "tuna",
    "tune",
    "turf",
    "turn",
    "twig",
    "twin",
    "type",
    "ugly",
    "undo",
    "unit",
    "upon",
    "urge",
    "used",
    "user",
    "vain",
    "vary",
    "vast",
    "veil",
    "vein",
    "verb",
    "very",
    "vest",
    "veto",
    "vice",
    "view",
    "visa",
    "void",
    "volt",
    "vote",
    "wade",
    "wage",
    "wait",
    "wake",
    "walk",
    "wall",
    "wand",
    "want",
    "ward",
    "ware",
    "warm",
    "warn",
    "warp",
    "wart",
    "wary",
    "wash",
    "wasp",
    "wave",
    "weak",
    "wear",
    "weed",
    "week",
    "weld",
    "well",
    "went",
    "were",
    "west",
    "whale",
    "wharf",
    "wheat",
    "wheel",
    "when",
    "whip",
    "whir",
    "whom",
    "wide",
    "wife",
    "wild",
    "will",
    "wind",
    "wine",
    "wing",
    "wink",
    "wipe",
    "wire",
    "wise",
    "wish",
    "with",
    "wolf",
    "wood",
    "wool",
    "word",
    "wore",
    "work",
    "worm",
    "worn",
    "wrap",
    "wren",
    "yard",
    "yarn",
    "yawn",
    "year",
    "yell",
    "yoga",
    "yolk",
    "your",
    "zeal",
    "zero",
    "zinc",
    "zone",
    "zoom",
]


class NanoIn(BaseModel):
    size: int = 21
    alphabet: str = _NANOID_ALPHABET


def _b32_crockford(value: int, length: int) -> str:
    out = []
    for _ in range(length):
        out.append(_CROCKFORD[value & 0x1F])
        value >>= 5
    return "".join(reversed(out))


def _ulid() -> str:
    # 48-bit ms timestamp -> 10 chars, 80-bit randomness -> 16 chars.
    ms = int(time.time() * 1000) & ((1 << 48) - 1)
    rnd = int.from_bytes(os.urandom(10), "big")
    return _b32_crockford(ms, 10) + _b32_crockford(rnd, 16)


@router.get("/id/uuid", summary="Generate v4 (random) or v7 (time-ordered) UUIDs")
def gen_uuid(
    version: int = Query(4, ge=1, le=7),
    count: int = Query(1, ge=1, le=100),
) -> dict:
    def one() -> str:
        if version == 4:
            return str(uuid.uuid4())
        if version == 7:
            # RFC 9562 v7: 48-bit ms timestamp + random
            ms = int(time.time() * 1000)
            rnd = os.urandom(10)
            b = ms.to_bytes(6, "big") + rnd
            lst = bytearray(b)
            lst[6] = (lst[6] & 0x0F) | 0x70
            lst[8] = (lst[8] & 0x3F) | 0x80
            return str(uuid.UUID(bytes=bytes(lst)))
        if version == 1:
            return str(uuid.uuid1())
        raise ToolError("Only UUID versions 1, 4 and 7 are supported.")

    return {"version": version, "ids": [one() for _ in range(count)]}


@router.get("/id/ulid", summary="Generate lexicographically sortable ULIDs")
def gen_ulid(count: int = Query(1, ge=1, le=100)) -> dict:
    return {"ids": [_ulid() for _ in range(count)]}


@router.post("/id/nanoid", summary="Generate URL-safe Nano IDs")
def gen_nanoid(body: NanoIn) -> dict:
    if not (2 <= body.size <= 256) or not (2 <= len(body.alphabet) <= 256):
        raise ToolError("size and alphabet length must be 2..256.")
    return {"id": "".join(secrets.choice(body.alphabet) for _ in range(body.size))}


@router.get("/password", summary="Generate a random password")
def gen_password(
    length: int = Query(20, ge=6, le=256),
    symbols: bool = True,
    digits: bool = True,
    uppercase: bool = True,
    count: int = Query(1, ge=1, le=50),
) -> dict:
    pool = "abcdefghijklmnopqrstuvwxyz"
    if uppercase:
        pool += "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    if digits:
        pool += "0123456789"
    if symbols:
        pool += "!@#$%^&*()-_=+[]{};:,.?/"
    pwds = ["".join(secrets.choice(pool) for _ in range(length)) for _ in range(count)]
    return {"passwords": pwds, "entropy_bits": round(length * math.log2(len(pool)), 1)}


@router.get("/passphrase", summary="Generate a word-based passphrase")
def gen_passphrase(
    words: int = Query(5, ge=3, le=12),
    separator: str = "-",
    capitalize: bool = False,
    add_number: bool = True,
) -> dict:
    picks = [secrets.choice(_WORDS) for _ in range(words)]
    if capitalize:
        picks = [w.capitalize() for w in picks]
    phrase = separator.join(picks)
    if add_number:
        phrase += separator + str(secrets.randbelow(100))
    return {
        "passphrase": phrase,
        "words": words,
        "entropy_bits": round(words * math.log2(len(_WORDS)), 1),
    }


@router.get("/password/strength", summary="Estimate password strength (entropy + heuristics)")
def strength(password: str) -> dict:
    classes = 0
    classes += any(c.islower() for c in password)
    classes += any(c.isupper() for c in password)
    classes += any(c.isdigit() for c in password)
    classes += any(not c.isalnum() for c in password)
    pool = {1: 26, 2: 52, 3: 62, 4: 94}.get(classes, 26)
    bits = round(len(password) * math.log2(pool), 1) if password else 0.0
    verdict = (
        "very weak"
        if bits < 28
        else "weak"
        if bits < 36
        else "reasonable"
        if bits < 60
        else "strong"
        if bits < 128
        else "very strong"
    )
    notes = []
    if len(password) < 12:
        notes.append("shorter than 12 characters")
    if len(set(password)) <= max(1, len(password) // 3):
        notes.append("many repeated characters")
    return {"length": len(password), "char_classes": classes, "entropy_bits": bits, "verdict": verdict, "notes": notes}


register(
    ToolInfo(
        key="idgen",
        title="IDs & passwords",
        category="Generators",
        description="UUID v1/v4/v7, ULID, Nano ID, random passwords & passphrases, strength estimate.",
        router=router,
        endpoints=[
            Endpoint("GET", "/v1/id/uuid", "UUIDs", "?version=7&count=3"),
            Endpoint("GET", "/v1/id/ulid", "ULIDs", "?count=3"),
            Endpoint("POST", "/v1/id/nanoid", "Nano IDs", '{"size":12}'),
            Endpoint("GET", "/v1/password", "Random password", "?length=24&symbols=true"),
            Endpoint("GET", "/v1/passphrase", "Passphrase", "?words=5"),
            Endpoint("GET", "/v1/password/strength", "Strength check", "?password=hunter2"),
        ],
    )
)
